import type { Metadata } from "next"
import "./globals.css"
import { I18nProvider } from "@/i18n"
import LanguageSwitcher from "@/components/LanguageSwitcher"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="zh">
      <body>
        <I18nProvider>
          <div className="p-4 text-right">
            <LanguageSwitcher />
          </div>
          {children}
        </I18nProvider>
      </body>
    </html>
  )
}
